#pragma once
/*
 *  Part of the Parabix Project, under the Open Software License 3.0.
 *  SPDX-License-Identifier: OSL-3.0
 *
 *  This file is generated by UCD_properties.py - manual edits may be lost.
 */

#include <utility>
namespace UCD {
	const auto UnicodeVersion = "14.0.0";
	using codepoint_t = unsigned;
	enum : codepoint_t { UNICODE_MAX = 0x10FFFF };
	using interval_t = std::pair<codepoint_t, codepoint_t>;
}

