#!/bin/bash
#
# Robert D. Cameron
#
# Usage: ./test_nfd 
#
test_dir=`echo "$0" | sed "s/[^\/]*$//"`

test_program=$1

output_directory=nfd_output

[ -x "$output_directory.bak" ] && rm -rf $output_directory.bak
[ -x "$output_directory" ] && mv $output_directory $output_directory.bak

mkdir $output_directory

$test_program ../All_good >$output_directory/All_good.nfd

diff -q $output_directory/All_good.nfd All_good.uconv
