#!/bin/bash
#
# Robert D. Cameron
#
# Usage: ./test_nfd 
#
test_dir=`echo "$0" | sed "s/[^\/]*$//"`

test_program=$1
input_directory=TestFiles
output_directory=nfd_output


[ -x "$output_directory.bak" ] && rm -rf $output_directory.bak
[ -x "$output_directory" ] && mv $output_directory $output_directory.bak

mkdir $output_directory

$test_program ../All_good >$output_directory/All_good.nfd

for f in $input_directory/*
do
   fbase=`echo $f | sed "s#$input_directory/##"`
   $test_program  $input_directory/$fbase >$output_directory/$fbase.nfd
done

echo "diff -q ExpectedOutput TestOutput"
diff -q ExpectedOutput nfd_output
